---
# install sesnu plugins
- name: install plugins
  command: sensu-install -p {{ item }}
  with_items:
    - cpu-checks
    - disk-checks
    - memory-checks 
    - process-checks
    - load-checks
    - vmstats 
    - nginx
    - stackstorm
